export default function AboutView() {
  return (
    <div>
      <div className="de-hero">
        <div className="de-hero__date-label">About</div>
        <div className="de-hero__date">Diamond Edge</div>
      </div>

      <div className="de-about">
        {/* Product */}
        <div className="de-about__section">
          <div className="de-about__section-title">What is this?</div>
          <p className="de-about__text">
            Diamond Edge is a read-only MLB betting intelligence dashboard. It visualises
            daily predictions generated by a Python machine learning pipeline — no bets are
            placed here, no bookmaker is integrated.
          </p>
          <p className="de-about__text">
            Every morning the pipeline runs, scores today's games, calculates edges against
            the market, and writes a JSON file. This app reads those files and presents them
            in a clean, mobile-first interface you can install to your home screen.
          </p>
        </div>

        {/* Model */}
        <div className="de-about__section">
          <div className="de-about__section-title">The Model</div>
          <ul className="de-about__list">
            <li>Logistic regression trained on 2025–2026 MLB season data</li>
            <li>32 features: rolling form, pitcher ERA/WHIP/K9, run differentials, ballpark factors</li>
            <li>No look-ahead: features use only data available before game time</li>
            <li>Walk-forward backtesting with date-based train/test split</li>
            <li>Edge = model probability − market implied probability</li>
            <li>Stake sizing: 1%–5% of bankroll based on edge tier</li>
          </ul>
        </div>

        {/* Edge tiers */}
        <div className="de-about__section">
          <div className="de-about__section-title">Edge Tiers & Stakes</div>
          {[
            { range: 'Below 3%', tier: 'PASS',   stake: '0%',  color: 'var(--muted)' },
            { range: '3–6%',     tier: 'LOW',    stake: '1%',  color: 'var(--skip)' },
            { range: '6–10%',    tier: 'MID',    stake: '2%',  color: 'var(--gold)' },
            { range: '10–15%',   tier: 'SOLID',  stake: '3%',  color: 'var(--accent)' },
            { range: '15–20%',   tier: 'STRONG', stake: '4%',  color: 'var(--bet)' },
            { range: '20%+',     tier: 'ELITE',  stake: '5%',  color: 'var(--bet)' },
          ].map(row => (
            <div
              key={row.tier}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                padding: '8px 0',
                borderBottom: '1px solid var(--line)',
                fontSize: 13,
              }}
            >
              <span style={{ color: 'var(--muted)', fontFamily: 'var(--font-mono)', fontSize: 12 }}>
                {row.range}
              </span>
              <span style={{ fontWeight: 700, color: row.color, letterSpacing: '0.05em' }}>
                {row.tier}
              </span>
              <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--text)', fontSize: 12 }}>
                {row.stake} stake
              </span>
            </div>
          ))}
        </div>

        {/* Data sources */}
        <div className="de-about__section">
          <div className="de-about__section-title">Data Sources</div>
          <ul className="de-about__list">
            <li>MLB Stats API — game results, team records, pitcher stats</li>
            <li>Odds API — market moneyline and run line odds from 20+ books</li>
            <li>Predictions written daily as static JSON files</li>
            <li>Results settled automatically after each game completes</li>
          </ul>
        </div>

        {/* Run line */}
        <div className="de-about__section">
          <div className="de-about__section-title">Run Line Selection</div>
          <p className="de-about__text">
            The model escalates to a run line bet (-1.5) when three conditions are met:
          </p>
          <ul className="de-about__list">
            <li>Model win probability &gt; 63%</li>
            <li>Moneyline odds are short (below 1.70 — poor value)</li>
            <li>Run line odds are at least 1.75 (worth the handicap)</li>
          </ul>
        </div>

        {/* Accumulators */}
        <div className="de-about__section">
          <div className="de-about__section-title">Accumulators</div>
          <p className="de-about__text">
            Doubles and trebles are built from the highest-edge qualifying picks each day.
            They run on a separate €100 accumulator bankroll and are tracked independently
            from single bets.
          </p>
        </div>

        {/* Disclaimer */}
        <div className="de-about__disclaimer">
          <div className="de-about__disclaimer-title">⚠ For informational use only</div>
          <p>
            This dashboard is a personal analytics tool. It does not constitute financial advice,
            betting advice, or any recommendation to place bets. All figures are simulated and
            for tracking purposes only. Gamble responsibly.
          </p>
        </div>

        {/* Version */}
        <div style={{ textAlign: 'center', padding: '16px 0 8px', color: 'var(--muted-dim)', fontSize: 11 }}>
          Diamond Edge · MLB Season 2026 · Static PWA
        </div>
      </div>
    </div>
  )
}
